services:
  - type: web
    name: yes-grad-service-app
    runtime: java
    buildCommand: ./gradlew clean bootJar
    startCommand: java -jar build/libs/app.jar
    envVars:
      - key: JAVA_VERSION
        value: 24
      - key: SPRING_PROFILES_ACTIVE
        value: prod